# Generated by Django 2.1.5 on 2019-01-17 21:27
import json

from django.db import migrations

from ..models import Mineral

def save_minerals_to_db(apps, schema_editor):

    with open('minerals.json') as mineral_file:
        data = json.load(mineral_file)

    for mineral in data:
        Mineral.objects.create(
            name = mineral.get('name', ''),
            image_filename = mineral.get('image filename', ''),
            image_caption = mineral.get('image caption', ''),
            category = mineral.get('category', ''),
            formula = mineral.get('formula', ''),
            strunz_class = mineral.get('strunz classification', ''),
            color = mineral.get('color', ''),
            crystal_system = mineral.get('crystal system', ''),
            unit_cell = mineral.get('unit cell', ''),
            crystal_symmetry = mineral.get('crystal symmetry', ''),
            cleavage = mineral.get('cleavage', ''),
            mohs_hardness = mineral.get('mohs scale hardness', ''),
            luster = mineral.get('luster', ''),
            streak = mineral.get('streak', ''),
            diaphaneity = mineral.get('diaphaneity', ''),
            optical_properties = mineral.get('optical properties', ''),
            refractive_index = mineral.get('refractive index', ''),
            crystal_habit = mineral.get('crystal habit', ''),
            specific_gravity = mineral.get('specific gravity', ''),
            group = mineral.get('group', '')
        )



class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_minerals_to_db)
    ]
